### ISSUE TITLE
Speech Recognition error on import

### ISSUE THREAD

**Issue by maryxyan** [a-real-ai/pywinassistant#6]
ERROR: Could not find a version that satisfies the requirement speech_recognition (from versions: none)
ERROR: No matching distribution found for speech_recognition

**Comment by maryxyan** [comment]
Solved with
pip install SpeechRecognition
[CaseSensitive]

**Comment by henyckma** [comment]
Thank you, I'm going to update the install requirements.

**Comment by JasonSmithdAzEru** [comment]
Facing same issue. Unfortunately still not working after updating installing. Still returning same error.

**Comment by maryxyan** [comment]
> Facing same issue. Unfortunately still not working after updating installing. Still returning same error.
> 

Maybe share a screenshot? 
Again it's Case Sensitive

**Comment by roberto-coscia** [comment]
![image](https://github.com/a-real-ai/pywinassistant/assets/156483604/5ed58580-9715-4505-9d09-e7cc9046ec09)
changed as adviced with SpeechRecognition on the assistant.py and the requirements.txt file and still getting the error

```
PS C:\Users\3Horizons\Desktop\vot\pywinassistant> python -m core.assistant              
Traceback (most recent call last):
  File "C:\Users\3Horizons\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\3Horizons\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\3Horizons\Desktop\vot\pywinassistant\core\assistant.py", line 6, in <module>
    import SpeechRecognition as sr
ModuleNotFoundError: No module named 'SpeechRecognition'
PS C:\Users\3Horizons\Desktop\vot\pywinassistant> 
```

requirements.txt file
![image](https://github.com/a-real-ai/pywinassistant/assets/156483604/5b706153-e618-49d8-89d3-5a9480e0bb50)

Python version installed : Python 3.8.1rc1

**Comment by saqib727** [comment]
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1006)'))': /simple/speechrecognition/


I'm getting Following error now. When i do : pip install SpeechRecognition
